
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'startA B LPAREN RPARENstart : seq\n| emptyseq : unit seq\n| unitunit : A Bunit : LPAREN seq RPARENempty :'
    
_lr_action_items = {'$end':([0,1,2,3,4,7,8,10,],[-7,0,-1,-2,-4,-3,-5,-6,]),'A':([0,4,6,8,10,],[5,5,5,-5,-6,]),'LPAREN':([0,4,6,8,10,],[6,6,6,-5,-6,]),'RPAREN':([4,7,8,9,10,],[-4,-3,-5,10,-6,]),'B':([5,],[8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'seq':([0,4,6,],[2,7,9,]),'empty':([0,],[3,]),'unit':([0,4,6,],[4,4,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> seq','start',1,'p_start','parser.py',9),
  ('start -> empty','start',1,'p_start','parser.py',10),
  ('seq -> unit seq','seq',2,'p_seq','parser.py',14),
  ('seq -> unit','seq',1,'p_seq','parser.py',15),
  ('unit -> A B','unit',2,'p_unit_ab','parser.py',19),
  ('unit -> LPAREN seq RPAREN','unit',3,'p_unit_paren','parser.py',23),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',27),
]
